"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[❯❯](dimmed white) "

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$sudo\
$fill\
$cmd_duration\
$docker_context\
$package\
$all\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$memory_usage\
$battery\
$time\
$line_break\
$jobs\
$status\
$os\
$container\
$shell\
$character"""

[aws]
symbol = "  "
format = ' [$symbol($profile )(\($region\) )(\[$duration\])]($style)'

[azure]
format = ' [$symbol($subscription)]($style)'

[battery]
format = ' [$symbol$percentage]($style)'

[buf]
symbol = " "
format = ' [$symbol($version)]($style)'

[bun]
format = ' [$symbol($version)]($style)'

[c]
symbol = " "
format = ' [$symbol($version(-$name))]($style)'

[cmake]
format = ' [$symbol($version)]($style)'

[cmd_duration]
format = ' [$duration]($style)'

[cobol]
format = ' [$symbol($version)]($style)'

[conda]
symbol = " "
format = ' [$symbol$environment]($style)'

[crystal]
symbol = " "
format = ' [$symbol($version)]($style)'

[daml]
format = ' [$symbol($version)]($style)'

[dart]
symbol = " "
format = ' [$symbol($version)]($style)'

[deno]
format = ' [$symbol($version)]($style)'

[directory]
read_only = " 󰌾"
truncation_length = 4

[docker_context]
symbol = " "
format = ' [$symbol$context]($style)'

[dotnet]
format = ' [$symbol($version )(🎯 $tfm)]($style)'

[elixir]
symbol = " "
format = ' [$symbol($version \(OTP $otp_version\))]($style)'

[elm]
symbol = " "
format = ' [$symbol($version)]($style)'

[erlang]
format = ' [$symbol($version)]($style)'

[fennel]
symbol = " "
format = ' [$symbol($version)]($style)'

[fill]
symbol = ' '

[fossil_branch]
symbol = " "
format = '[$symbol$branch]($style) '

[gcloud]
format = ' [$symbol$account(@$domain )(\($region\))]($style)'

[git_branch]
symbol = " "
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_commit]
tag_symbol = '  '

[gleam]
format = ' [$symbol($version)]($style)'

[golang]
symbol = " "
format = ' [$symbol($version)]($style)'

[guix_shell]
symbol = " "
format = '[$symbol]($style)'

[gradle]
symbol = " "
format = ' [$symbol($version)]($style)'

[haskell]
symbol = " "
format = ' [$symbol($version)]($style)'

[haxe]
symbol = " "
format = ' [$symbol($version)]($style)'

[helm]
format = ' [$symbol($version)]($style)'

[hg_branch]
symbol = " "
format = '[$symbol$branch(:$topic)]($style) '

[hostname]
ssh_symbol = " "
format = '[$ssh_symbol$hostname]($style) '

[java]
symbol = " "
format = ' [${symbol}(${version})]($style)'

[julia]
symbol = " "
format = ' [$symbol($version)]($style)'

[kotlin]
symbol = " "
format = ' [$symbol($version)]($style)'

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) '

[lua]
symbol = " "
format = ' [$symbol($version)]($style)'

[memory_usage]
symbol = "󰍛 "
format = ' $symbol [${ram}( | ${swap})]($style)'

[meson]
symbol = "󰔷 "
format = ' [$symbol$project]($style)'

[mojo]
format = ' [$symbol($version)]($style)'

[nats]

[nim]
symbol = "󰆥 "
format = ' [$symbol($version)]($style)'

[nix_shell]
symbol = " "
format = ' [$symbol$state( \($name\))]($style)'

[nodejs]
symbol = " "
format = ' [$symbol($version)]($style)'

[ocaml]
symbol = " "
format = ' [$symbol($version )(\($switch_indicator$switch_name\))]($style)'

[odin]
format = ' [$symbol($version)]($style)'

[opa]
format = ' [$symbol($version)]($style)'

[openstack]
format = ' [$symbol$cloud(\($project\))]($style)'

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
format = ' [$symbol$version]($style)'

[perl]
symbol = " "
format = ' [$symbol($version)]($style)'

[php]
symbol = " "
format = ' [$symbol($version)]($style)'

[pijul_channel]
symbol = " "
format = '[$symbol$channel]($style) '

[pulumi]
format = ' [$symbol($username@)$stack]($style)'

[purescript]
format = ' [$symbol($version)]($style)'

[python]
symbol = " "
format = ' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'

[quarto]
format = ' [$symbol($version)]($style)'

[raku]
format = ' [$symbol($version-$vm_version)]($style)'

[red]
format = ' [$symbol($version)]($style)'

[rlang]
symbol = "󰟔 "
format = ' [$symbol($version)]($style)'

[ruby]
symbol = " "
format = ' [$symbol($version)]($style)'

[rust]
symbol = "󱘗 "
format = ' [$symbol($version)]($style)'

[scala]
symbol = " "
format = ' [${symbol}(${version})]($style)'

[solidity]
format = ' [$symbol($version)]($style)'

[spack]
format = ' [$symbol$environment]($style)'

[sudo]
format = '[$symbol]($style) '

[swift]
symbol = " "
format = ' [$symbol($version)]($style)'

[terraform]
format = ' [$symbol$workspace]($style)'

[time]
format = ' [$time]($style)'

[typst]
format = ' [$symbol($version)]($style)'

[username]
format = ' [$user]($style)'

[vagrant]
format = ' [$symbol($version)]($style)'

[vcsh]

[vlang]
format = ' [$symbol($version)]($style)'

[zig]
symbol = " "
format = ' [$symbol($version)]($style)'
